[book]
authors = ["qaqland"]
language = "zh-Hans"
multilingual = false
src = "src"
title = "qaqLand"
description = "Site for qaqland and his venlafaxine."

[output.html]
git-repository-url = "https://github.com/qaqland/qaqland"
edit-url-template = "https://github.com/qaqland/qaqland/edit/main/{path}"
cname = "qaq.land"
no-section-label = true